### ISSUE TITLE
Addressing Significant Cumulative Errors with UrbanLoco Dataset

### ISSUE THREAD

**Issue by YWL0720** [vectr-ucla/direct_lidar_inertial_odometry#13]
Hi!  I have tested your algorithm using Dataset 5: HK-Data20190117 from the [UrbanLoco dataset](https://github.com/weisongwen/UrbanLoco). However, I noticed significant cumulative errors when the vehicle returns to the starting point. Below are the parameters I used. Could you please advise on how to adjust them for better performance? Thank you.
![Screenshot from 2023-07-07 11-25-19](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65143504/fb0d379f-6821-431d-bbb2-c8626725ae1f)
![Screenshot from 2023-07-07 11-25-54](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65143504/ec70ecb1-6fb1-4c3d-b23a-8e13df84f214)
```
dlio:

  frames:
    odom: odom
    baselink: base_link
    lidar: lidar
    imu: imu

  map:
    waitUntilMove: true
    dense:
      filtered: false
    sparse:
      frequency: 1.0
      leafSize: 0.25

  odom:

    gravity: 9.80665

    imu:
      approximateGravity: false
      calibration:
        gyro: true
        accel: true
        time: 3
      bufferSize: 5000

    preprocessing:
      cropBoxFilter:
        size: 1.0
      voxelFilter:
        res: 0.25

    keyframe:
      threshD: 1.0
      threshR: 45.0

    submap:
      useJaccard: true
      keyframe:
        knn: 10
        kcv: 10
        kcc: 10
    gicp:
      minNumPoints: 64
      kCorrespondences: 16
      maxCorrespondenceDistance: 0.5
      maxIterations: 32
      transformationEpsilon: 0.01
      rotationEpsilon: 0.01
      initLambdaFactor: 1e-9

    geo:
      Kp: 4.5
      Kv: 11.25
      Kq: 4.0
      Kab: 2.25
      Kgb: 1.0
      abias_max: 5.0
      gbias_max: 0.5
```
